version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: tallydb-intern-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=InternPassword123#
      - MSSQL_PID=Express
    ports:
      - "1434:1433"
    volumes:
      - ./python_docs:/var/opt/mssql/backup
      - sqlserver_data:/var/opt/mssql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P InternPassword123# -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  sqlserver_data:
